version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  resource:
    build: ./server
    links:
      - db
    ports:
      - "3300:3300"
    environment:
      - "DB_HOST=${DOCKER_HOST_IP}"
      - "BOOTSTRAP=${BOOTSTRAP}"
    depends_on:
      db:
        condition: service_healthy
  web:
    build: ./client
    ports:
      - "8080:8080"
